# Configuration spécifique de développement
# Utilisé avec --config _config.yml,_config_dev.yml

# Activer le cache busting pour forcer le rechargement des assets
cache_busting: true

# Activer le mode développement
environment: development

# Optimisations à désactiver en dev
compress_html:
  enabled: false

# Désactiver Google Analytics en dev
google_analytics: ""

# Boost perf en dev
future: true
limit_posts: 5

# LiveReload
livereload: true
